const BASE_URL = "http://127.0.0.1:5000/";

const USER_BASE_URL = BASE_URL + "auth/";

const LOGIN_URL = USER_BASE_URL + "login/student/";

const REGISTER_URL = USER_BASE_URL + "register/"

const COURSE_URL = BASE_URL + "course/"

const MAJORS_URL = COURSE_URL + "majors/"

const OPTIONAL_COURSES_URL = COURSE_URL + "options/"

const OPTIONAL_COURSES_CHOOSE_URL = COURSE_URL + "update/"

const GET_ALL_COURSES_URL = COURSE_URL + "all/"

const MASHOV_BASE_URL = BASE_URL + "mashov/"

const GET_ATTENDANCE_URL = MASHOV_BASE_URL + "attendence/"

const GET_TESTS_URL = MASHOV_BASE_URL + "tests/"

const GET_ASSIGNMENTS_URL = MASHOV_BASE_URL + "assignments/"

//teacher

const TEACHER_MASHOV_BASE = MASHOV_BASE_URL + "teacher/"

const GET_ALL_STUDENTS = TEACHER_MASHOV_BASE + "students/"

const TEACHER_LOGIN = USER_BASE_URL + "login/teacher/"

const CREATE_TEST = TEACHER_MASHOV_BASE + "test/"

const CREATE_LESSON = TEACHER_MASHOV_BASE + "lesson/"

const GET_TEACHER_COURSES = TEACHER_MASHOV_BASE + "courses/"

const GET_STUDENTS_INFO = TEACHER_MASHOV_BASE + "studentinfo/"

//classroom

const CLASSROOM_BASE_URL = BASE_URL + "classroom/"

const GET_ASSIGNMENTS_BY_COURSE = CLASSROOM_BASE_URL + "assignments/"

const UPLOAD_FILE = CLASSROOM_BASE_URL + "upload/"

export {
    USER_BASE_URL,
    LOGIN_URL,
    REGISTER_URL,
    COURSE_URL,
    MAJORS_URL,
    OPTIONAL_COURSES_URL,
    OPTIONAL_COURSES_CHOOSE_URL,
    GET_ALL_COURSES_URL,
    GET_ATTENDANCE_URL,
    GET_TESTS_URL,
    GET_ASSIGNMENTS_URL,
    GET_ALL_STUDENTS,
    TEACHER_LOGIN,
    CREATE_TEST,
    CREATE_LESSON,
    GET_TEACHER_COURSES,
    GET_STUDENTS_INFO,
    GET_ASSIGNMENTS_BY_COURSE,
    UPLOAD_FILE,
    CLASSROOM_BASE_URL
}